# Trigger when commits are pushed to the master branch

on:
  push:
    branches:
      - release
  workflow_dispatch:


jobs:
  hubapp-release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@master

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs-material
        
    - name: Build page   
      run: mkdocs gh-deploy --force
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

